#!/usr/bin/env bash

# Set the key file name and passphrase
key_file="school"
passphrase="betty"

# Create RSA key pair with 4096 bits and passphrase protection
ssh-keygen -t rsa -b 4096 -f ~/.ssh/$key_file -N "$passphrase"

echo "RSA key pair created successfully."
echo "Private key saved to: ~/.ssh/$key_file"
