#!/usr/bin/env bash

# Set the key file name and passphrase
key_file="school"
passphrase="betty"

# Specify the full path for the private key file
private_key_file="~/.ssh/$key_file"

# Create RSA key pair with 4096 bits and passphrase protection
ssh-keygen -t rsa -b 4096 -f "$private_key_file" -N "$passphrase"

echo "RSA key pair created successfully."
echo "Private key saved to: $private_key_file"
